### PR TITLE
Release/v0.0.2

### PR DESCRIPTION
**Pull request by slettner**
v0.0.1 does not have the cloudwatch code plus the `S3` class has been renamed. 
It would be nice to have a tagged version of the new code so that we can update downstream users.

This is to avoid problems like https://github.com/jina-ai/cloud-helper/issues/5

### CODE REVIEW

**Review by jacobowitz — APPROVED** [review]
lgtm, I think you also need to fix the 0.2.0 tag then?

**Comment by slettner** [comment]
I have created a tag for 0.0.2, that should be sufficient right?

**Comment by jacobowitz** [comment]
ah I see you tagged the commits in this branch, yes that should work, although its slightly awkward to do it like this. I would have waited until this is merged and then tag master. Because this PR will create a new commit (the merge commit for this PR) and this one will not be part of your 0.2.0 tag then?

**Comment by slettner** [comment]
Oh yes that is true, I will do it like you said in the future, makes more sense :)

**Pull request merged**
